# Generated by Django 2.2.5 on 2019-10-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('tel1', models.CharField(max_length=255)),
                ('tel2', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('job', models.CharField(blank=True, default=',', max_length=255)),
                ('sitename', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
