# Generated by Django 2.2.5 on 2019-10-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duty', models.CharField(blank=True, default=',', max_length=255)),
                ('room', models.CharField(blank=True, default='', max_length=255)),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
    ]
